2022-07-18 10:20:28,311 p=1302 u=root n=ansible | Starting galaxy collection install process
2022-07-18 10:20:28,665 p=1302 u=root n=ansible | Process install dependency map
2022-07-18 10:20:28,712 p=1302 u=root n=ansible | |
2022-07-18 10:20:28,814 p=1302 u=root n=ansible | /
2022-07-18 10:20:28,915 p=1302 u=root n=ansible | -
2022-07-18 10:20:29,016 p=1302 u=root n=ansible | \
2022-07-18 10:20:29,118 p=1302 u=root n=ansible | |
2022-07-18 10:20:29,226 p=1302 u=root n=ansible | /
2022-07-18 10:20:29,328 p=1302 u=root n=ansible | -
2022-07-18 10:20:29,429 p=1302 u=root n=ansible | \
2022-07-18 10:20:29,530 p=1302 u=root n=ansible | |
2022-07-18 10:20:29,631 p=1302 u=root n=ansible | /
2022-07-18 10:20:29,733 p=1302 u=root n=ansible | -
2022-07-18 10:20:29,834 p=1302 u=root n=ansible | \
2022-07-18 10:20:29,935 p=1302 u=root n=ansible | |
2022-07-18 10:20:30,036 p=1302 u=root n=ansible | /
2022-07-18 10:20:30,137 p=1302 u=root n=ansible | -
2022-07-18 10:20:30,239 p=1302 u=root n=ansible | \
2022-07-18 10:20:30,340 p=1302 u=root n=ansible | |
2022-07-18 10:20:30,442 p=1302 u=root n=ansible | /
2022-07-18 10:20:30,543 p=1302 u=root n=ansible | -
2022-07-18 10:20:30,644 p=1302 u=root n=ansible | \
2022-07-18 10:20:30,746 p=1302 u=root n=ansible | |
2022-07-18 10:20:30,847 p=1302 u=root n=ansible | /
2022-07-18 10:20:30,948 p=1302 u=root n=ansible | -
2022-07-18 10:20:31,049 p=1302 u=root n=ansible | \
2022-07-18 10:20:31,151 p=1302 u=root n=ansible | |
2022-07-18 10:20:31,252 p=1302 u=root n=ansible | /
2022-07-18 10:20:31,353 p=1302 u=root n=ansible | -
2022-07-18 10:20:31,455 p=1302 u=root n=ansible | \
2022-07-18 10:20:31,556 p=1302 u=root n=ansible | |
2022-07-18 10:20:31,657 p=1302 u=root n=ansible | /
2022-07-18 10:20:31,758 p=1302 u=root n=ansible | -
2022-07-18 10:20:31,860 p=1302 u=root n=ansible | \
2022-07-18 10:20:31,961 p=1302 u=root n=ansible | |
2022-07-18 10:20:32,062 p=1302 u=root n=ansible | /
2022-07-18 10:20:32,164 p=1302 u=root n=ansible | -
2022-07-18 10:20:32,265 p=1302 u=root n=ansible | \
2022-07-18 10:20:32,366 p=1302 u=root n=ansible | |
2022-07-18 10:20:32,467 p=1302 u=root n=ansible | /
2022-07-18 10:20:32,568 p=1302 u=root n=ansible | -
2022-07-18 10:20:32,670 p=1302 u=root n=ansible | \
2022-07-18 10:20:32,771 p=1302 u=root n=ansible | |
2022-07-18 10:20:32,872 p=1302 u=root n=ansible | /
2022-07-18 10:20:32,973 p=1302 u=root n=ansible | -
2022-07-18 10:20:33,074 p=1302 u=root n=ansible | \
2022-07-18 10:20:33,176 p=1302 u=root n=ansible | |
2022-07-18 10:20:33,278 p=1302 u=root n=ansible | /
2022-07-18 10:20:33,379 p=1302 u=root n=ansible | -
2022-07-18 10:20:33,481 p=1302 u=root n=ansible | \
2022-07-18 10:20:33,582 p=1302 u=root n=ansible | |
2022-07-18 10:20:33,683 p=1302 u=root n=ansible | /
2022-07-18 10:20:33,784 p=1302 u=root n=ansible | -
2022-07-18 10:20:33,887 p=1302 u=root n=ansible | Starting collection install process
2022-07-18 10:20:33,887 p=1302 u=root n=ansible | |
2022-07-18 10:20:33,888 p=1302 u=root n=ansible | Downloading https://galaxy.ansible.com/download/check_point-mgmt-3.1.0.tar.gz to /root/.ansible/tmp/ansible-local-130223ydy1vr/tmp9huhh_fe/check_point-mgmt-3.1.0-ex56w0vm
2022-07-18 10:20:33,988 p=1302 u=root n=ansible | /
2022-07-18 10:20:34,090 p=1302 u=root n=ansible | -
2022-07-18 10:20:34,191 p=1302 u=root n=ansible | \
2022-07-18 10:20:34,292 p=1302 u=root n=ansible | |
2022-07-18 10:20:34,394 p=1302 u=root n=ansible | /
2022-07-18 10:20:34,495 p=1302 u=root n=ansible | -
2022-07-18 10:20:34,596 p=1302 u=root n=ansible | \
2022-07-18 10:20:34,696 p=1302 u=root n=ansible | |
2022-07-18 10:20:34,798 p=1302 u=root n=ansible | /
2022-07-18 10:20:34,899 p=1302 u=root n=ansible | -
2022-07-18 10:20:35,001 p=1302 u=root n=ansible | \
2022-07-18 10:20:35,102 p=1302 u=root n=ansible | |
2022-07-18 10:20:35,203 p=1302 u=root n=ansible | /
2022-07-18 10:20:35,303 p=1302 u=root n=ansible | -
2022-07-18 10:20:35,405 p=1302 u=root n=ansible | \
2022-07-18 10:20:35,506 p=1302 u=root n=ansible | |
2022-07-18 10:20:35,607 p=1302 u=root n=ansible | /
2022-07-18 10:20:35,708 p=1302 u=root n=ansible | -
2022-07-18 10:20:35,810 p=1302 u=root n=ansible | \
2022-07-18 10:20:35,912 p=1302 u=root n=ansible | |
2022-07-18 10:20:36,013 p=1302 u=root n=ansible | /
2022-07-18 10:20:36,115 p=1302 u=root n=ansible | -
2022-07-18 10:20:36,216 p=1302 u=root n=ansible | \
2022-07-18 10:20:36,317 p=1302 u=root n=ansible | |
2022-07-18 10:20:36,418 p=1302 u=root n=ansible | /
2022-07-18 10:20:36,519 p=1302 u=root n=ansible | -
2022-07-18 10:20:36,620 p=1302 u=root n=ansible | \
2022-07-18 10:20:36,722 p=1302 u=root n=ansible | |
2022-07-18 10:20:36,823 p=1302 u=root n=ansible | /
2022-07-18 10:20:36,925 p=1302 u=root n=ansible | -
2022-07-18 10:20:37,026 p=1302 u=root n=ansible | \
2022-07-18 10:20:37,127 p=1302 u=root n=ansible | |
2022-07-18 10:20:37,229 p=1302 u=root n=ansible | Installing 'check_point.mgmt:3.1.0' to '/root/.ansible/collections/ansible_collections/check_point/mgmt'
2022-07-18 10:20:37,232 p=1302 u=root n=ansible | /
2022-07-18 10:20:37,332 p=1302 u=root n=ansible | -
2022-07-18 10:20:37,434 p=1302 u=root n=ansible | \
2022-07-18 10:20:37,535 p=1302 u=root n=ansible | |
2022-07-18 10:20:37,636 p=1302 u=root n=ansible | /
2022-07-18 10:20:37,737 p=1302 u=root n=ansible | -
2022-07-18 10:20:37,838 p=1302 u=root n=ansible | \
2022-07-18 10:20:37,939 p=1302 u=root n=ansible | |
2022-07-18 10:20:38,040 p=1302 u=root n=ansible | /
2022-07-18 10:20:38,141 p=1302 u=root n=ansible | -
2022-07-18 10:20:38,242 p=1302 u=root n=ansible | \
2022-07-18 10:20:38,343 p=1302 u=root n=ansible | check_point.mgmt:3.1.0 was installed successfully
2022-07-18 10:21:10,381 p=1313 u=root n=ansible | ERROR! 'cp_mgmt_show_tasks' is not a valid attribute for a Play

The error appears to be in '/ansible_dir/playbooks/mgmt_show.yaml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: show-tasks
  ^ here

2022-07-18 10:21:50,886 p=1319 u=root n=ansible | ERROR! couldn't resolve module/action 'cp_mgmt_show_tasks'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/ansible_dir/playbooks/mgmt_show.yaml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: show-tasks
    ^ here

2022-07-18 10:23:31,642 p=1372 u=root n=ansible | PLAY [all] *************************************************************************************************************************************************************
2022-07-18 10:23:33,024 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:33,129 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:34,798 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:36,005 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:45,282 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:45,287 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:45,294 p=1378 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:45,304 p=1372 u=root n=ansible | TASK [Gathering Facts] *************************************************************************************************************************************************
2022-07-18 10:23:45,306 p=1372 u=root n=ansible | ok: [192.168.1.5]
2022-07-18 10:23:46,733 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:46,956 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:47,847 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:23:53,940 p=1372 u=root n=ansible | fatal: [43.204.231.150]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

credssp: HTTPConnectionPool(host='43.204.231.150', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f14eac2bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))

2022-07-18 10:24:02,288 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:03,427 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:04,035 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:04,042 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 232, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1365, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 1244, in _find_module_utils
    shebang, interpreter = _get_shebang(u'/usr/bin/python', task_vars, templar, remote_is_local=remote_is_local)
  File "/usr/lib/python3/dist-packages/ansible/executor/module_common.py", line 634, in _get_shebang
    raise InterpreterDiscoveryRequiredError("interpreter discovery needed", interpreter_name=interpreter_name, discovery_mode=interpreter_out)
ansible.executor.interpreter_discovery.InterpreterDiscoveryRequiredError: <unprintable InterpreterDiscoveryRequiredError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:05,385 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:06,536 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:07,249 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:08,128 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:08,131 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:08,136 p=1381 u=root n=urllib3.connectionpool | Failed to parse headers (url=http://192.168.1.5:5985/wsman): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2022-07-18 10:24:08,141 p=1372 u=root n=ansible | TASK [show-tasks] ******************************************************************************************************************************************************
2022-07-18 10:24:08,143 p=1372 u=root n=ansible | [WARNING]: No python interpreters found for host 192.168.1.5 (tried ['python3.10', 'python3.9', 'python3.8', 'python3.7', 'python3.6', 'python3.5', '/usr/bin/python3',
'/usr/libexec/platform-python', 'python2.7', 'python2.6', '/usr/bin/python', 'python'])

2022-07-18 10:24:08,185 p=1372 u=root n=ansible | fatal: [192.168.1.5]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Exception calling "Create" with "1" argument(s): "At line:4 char:21
+ def _ansiballz_main():
+                     ~
An expression was expected after '('.
At line:8 char:19
+         os.getcwd()
+                   ~
An expression was expected after '('.
At line:20 char:27
+     except (AttributeError, OSError):
+                           ~
Missing argument in parameter list.
At line:22 char:29
+     excludes = set(('', '.', scriptdir))
+                             ~
Missing expression after ','.
At line:22 char:30
+     excludes = set(('', '.', scriptdir))
+                              ~~~~~~~~~
Unexpected token 'scriptdir' in expression or statement.
At line:22 char:29
+     excludes = set(('', '.', scriptdir))
+                             ~
Missing closing ')' in expression.
At line:22 char:39
+     excludes = set(('', '.', scriptdir))
+                                       ~
Unexpected token ')' in expression or statement.
At line:22 char:40
+     excludes = set(('', '.', scriptdir))
+                                        ~
Unexpected token ')' in expression or statement.
At line:29 char:7
+     if sys.version_info < (3,):
+       ~
Missing '(' after 'if' in if statement.
At line:29 char:30
+     if sys.version_info < (3,):
+                              ~
Missing expression after ','.
Not all parse errors were reported.  Correct the reported errors and try again."
At line:10 char:1
+ $exec_wrapper = [ScriptBlock]::Create($split_parts[0])
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command 
name, a script block, or a CommandInfo object.
At line:11 char:2
+ &$exec_wrapper
+  ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression
 

2022-07-18 10:24:08,194 p=1372 u=root n=ansible | PLAY RECAP *************************************************************************************************************************************************************
2022-07-18 10:24:08,195 p=1372 u=root n=ansible | 192.168.1.5                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2022-07-18 10:24:08,196 p=1372 u=root n=ansible | 43.204.231.150             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
